# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: def

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0
      env:
        DOTNET_INSTALL_DIR: D:\dotnet


    - name: Restore dependencies
      run: dotnet restore
        
    - name: Build
      run: dotnet build --no-restore
      #updated
    - name: Test
      run: dotnet test tests/UnitTests/UnitTests.csproj --configuration Debug --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Extract Code Coverage Percentage
      id: coverage
      shell: cmd
      run: |
        @echo off
        setlocal enabledelayedexpansion

        if not exist "tests\UnitTests\coverage.opencover.xml" (
        echo Coverage file not found!
        exit /b 1
        )

        for /f "tokens=2 delims=\"" %%A in ('findstr "sequenceCoverage" tests\UnitTests\coverage.opencover.xml') do (
        set "COVERAGE=%%A"
        )

        echo Extracted Code Coverage: !COVERAGE!
        echo percentage=!COVERAGE! >> %GITHUB_ENV%

    - name: Display Code Coverage
      shell: cmd
      run: |
        echo "Coverage is ${{ env.percentage }}%""
        
    - name: Verify Coverage Threshold
      shell: cmd
      run: |
          if ${{ env.percentage }} LSS 80 (
          echo Coverage ${{ env.percentage }}% is below the threshold (80%).
          exit /b 1
            )
