# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: def

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0
      env:
        DOTNET_INSTALL_DIR: D:\dotnet


    - name: Restore dependencies
      run: dotnet restore
        
    - name: Build
      run: dotnet build --no-restore
      #updated
    - name: Test
      run: dotnet test tests/UnitTests/UnitTests.csproj --configuration Debug --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Extract Code Coverage Percentage
      id: coverage
      run: |
            $coverage = (Select-Xml -Path "D:\Agents\github_runner\new runner\actions-runner-win-x64-2.321.0\_work\NewRepo\NewRepo\tests\UnitTests\coverage.opencover.xml" -XPath "//CoverageSession/Summary" | Select-Object -ExpandProperty Node).GetAttribute("sequenceCoverage")
            Write-Host "Code Coverage: $coverage%"
            echo "percentage=$coverage" >> $GITHUB_ENV
    
    - name: Display Code Coverage
      run: echo "Code Coverage is ${{ env.percentage }}%"

      # Step 7: Check Coverage Threshold
    - name: Verify Coverage Threshold
      if: ${{ env.percentage < 4 }} # Replace 80 with your desired threshold
      run: |
        echo "Coverage ${{ env.percentage }}% is below the threshold (80%)."
        exit 1
