# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: def

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0
      env:
        DOTNET_INSTALL_DIR: D:\dotnet
        
    - name: Restore dependencies
      run: dotnet restore
        
    - name: Build
      run: dotnet build --no-restore
      #updated
    - name: Test
      run: dotnet test tests/UnitTests/UnitTests.csproj --configuration Debug --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Extract code coverage percentage
      id: coverage
      shell: cmd
      run: |
        @echo off
        REM Find the coverage file
        for /r .\TestResults %%f in (coverage.opencover.xml) do (
          set coverageFile=%%f
          goto :found
        )
        :found
        if not exist "%coverageFile%" (
          echo Coverage file not found.
          exit /b 1
        )

        REM Extract the coverage percentage from the XML file
        for /f "tokens=2 delims==<>" %%a in ('findstr Linecoverage "%coverageFile%"') do (
          set coveragePercentage=%%a
        )

        REM Calculate the percentage (multiply by 100)
        for /f "tokens=1,2 delims=." %%a in ("%coveragePercentage%") do (
          set /a coveragePercentage=%%a * 100
        )

        echo Code Coverage Percentage: %coveragePercentage%%

        REM Check if coverage is less than 80%
        if %coveragePercentage% LSS 80 (
          echo Code coverage is less than 80%. Failing the job.
          exit /b 1
        ) else (
          echo Code coverage is 80%% or higher. Job passed.
