# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: def

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0
      env:
        DOTNET_INSTALL_DIR: D:\dotnet


    - name: Restore dependencies
      run: dotnet restore
        
    - name: Build
      run: dotnet build --no-restore
      #updated
    - name: Test
      run: dotnet test tests/UnitTests/UnitTests.csproj --configuration Debug --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Extract Code Coverage Percentage
      id: coverage
      shell: pwsh
      run: |
          # Ensure the file exists
          if (Test-Path "tests/UnitTests/coverage.opencover.xml") {
            $coverage = (Select-Xml -Path "tests/UnitTests/coverage.opencover.xml" -XPath "//CoverageSession/Summary").Node.GetAttribute("sequenceCoverage")
            Write-Host "Extracted Code Coverage: $coverage%"
            echo "percentage=$coverage" >> $GITHUB_ENV
          } else {
            Write-Host "Coverage file not found!"
            exit 1
          }

    - name: Display Code Coverage
      run: |
        echo "Code coverage is $percentage"
        echo "${{ env.percentage }}%"
        
    - name: Verify Coverage Threshold
      if: ${{ env.percentage != '' && fromJSON(env.percentage) < 80 }}
      run: |
          echo "Coverage ${{ env.percentage }}% is below the threshold (80%)."
          exit 1
